### ISSUE TITLE
Prepare Solidus Digital for Solidus 3.0

### ISSUE THREAD

**Issue by kennyadsl** [solidusio-contrib/solidus_digital#19]
Update this extension so that it works with Solidus 3.0 by making sure the specs pass.

**Comment by adammathys** [comment]
@derrickp and myself are going to pick this up.

**Comment by jarednorman** [comment]
Ha, I pulled it down to look at what was up with the factory loading. 😅

**Comment by seand7565** [comment]
Looks like this was closed by #20 - thanks! 🎉
